import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "../components/Layout";
import Navbar from "@/components/Navbar";
import { CotizarContextProvider } from "@/contexts/CotizarContext";
import HomePage from "@/components/HomePage";


export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>CODREMEX</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      
        <Navbar />
        <HomePage />
      
    </>
  );
}
