import Head from "next/head";

import Navbar from "../components/Navbar";

export default function About() {
  return (
    <>
      <Head>
        <title>CODREMEX - Nosotros</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section className="text-gray-600 body-font">
          <div className="container px-5 py-24 mx-auto">
            <div className="flex flex-col text-center w-full mb-20">
              <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
                Nuestra Empresa
              </h1>
              <p className="lg:w-2/3 mx-auto leading-relaxed text-base">
                CODREMEX es una empresa 100% mexicana, fundada y establecida en
                Ciudad Obregón, Sonora en 2019, dedicada a la comercialización
                de elementos de ingeniería hidráulica. Proveemos soluciones
                integrales para la conducción de agua a nivel nacional. Nos
                distinguimos por ofrecer productos de la más alta calidad
                disponible en el mercado, así como brindar asesoría técnica
                experta para su proyecto.
              </p>
            </div>
            <div className="flex flex-wrap">
              <div className="xl: lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
                <h2 className="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">
                  MISIÓN
                </h2>
                <p className="leading-relaxed text-base mb-4">
                  Nuestra misión es ser la principal empresa mercantilizadora de
                  productos hidráulicos en el norte del país, ofreciendo
                  soluciones integrales a nuestros clientes mediante la
                  comercialización de los mejores productos nacionales e
                  internacionales y la consultoría especializada en temas
                  hidráulicos. Nos comprometemos a mantener y ampliar nuestra
                  presencia en el estado de Sonora, y a generar empleos que
                  promuevan el bienestar y desarrollo de nuestros trabajadores y
                  sus familias, así como contribuir al desarrollo económico y
                  social de la región.
                </p>
              </div>
              <div className="xl: lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
                <h2 className="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">
                  VISIÓN
                </h2>
                <p className="leading-relaxed text-base mb-4">
                  Nos consolidaremos como líderes del mercado nacional en el
                  ámbito de los productos hidráulicos, reconocidos por ofrecer
                  soluciones integrales y de alta calidad que superen las
                  expectativas de nuestros clientes. Nos esforzaremos por
                  mantenernos a la vanguardia tecnológica y de innovación en el
                  sector, así como por cumplir con los más altos estándares de
                  calidad y seguridad. Nuestra meta es ser reconocidos como un
                  referente en el mercado, gracias a nuestro compromiso con la
                  excelencia y la satisfacción del cliente.
                </p>
              </div>
            </div>
          </div>
          <div className="flex flex-col text-center w-full mb-20">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
              Compromiso con el cliente
            </h1>
            <p className="lg:w-1/4 mx-auto leading-relaxed text-base">
              Nuestro compromiso principal es la satisfacción de nuestros
              clientes, por lo que trabajamos constantemente para brindarles
              soluciones integrales y de alta calidad que superen sus
              expectativas.
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
