import React from 'react'

const Head = () => {
  return (
    <div>
        <Head>
        <title>CODREMEX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default Head